BOT_LIST:
  - BLUM:
      BOT_USERNAME: BlumCryptoBot
      REF_URL: https://t.me/blum/app?startapp=ref_YbE9XKVsqA
      CLICKABLE_SELECTOR:
        - "#app > div.daily-reward-page.page.no-padding > div > div.pages-daily-reward-reward > div.footer > div.kit-fixed-wrapper.no-layout-tabs > button"
        - "#app > div.index-page.page > div > div.kit-fixed-wrapper.has-layout-tabs > div > button"

  - MAJOR:
      BOT_USERNAME: BlumCryptoBot
      REF_URL: https://t.me/major/start?startapp=5024522783
      CLICKABLE_SELECTOR:
        - "#root > div > div > div.px-8.mb-\[44px\] > button"
        - "#root > div > div > div > div > div.top-0.left-0.h-dvh.w-dvw.z-\[2\].fixed > div > div.container.false > button"

  - MIDAS:
      BOT_USERNAME: MidasRWA_bot
      REF_URL: https://t.me/MidasRWA_bot/app?startapp=ref_e40c3d56-72bd-43fa-968e-1d7b5f426353
      CLICKABLE_SELECTOR:
        - "#root > div.tgui-6a12827a138e8827.grid > div > div.flex.h-\[48px\].justify-stretch > button"
        - "#root > div.tgui-6a12827a138e8827.grid > div > div.z-10.flex.flex-1.flex-col.justify-between.gap-2 > button"

  - CATS:
      BOT_USERNAME: catsgang_bot
      REF_URL: https://t.me/catsgang_bot/join?startapp=bvGRSNi8ZfQfJp0mjqZqR
      CLICKABLE_SELECTOR:
        - "#root > div > div > button"
        - "#root > div > div > div.grow.pb-\[70px\] > div > div.grid.w-full.bg-gradient-orange-linear.text-white > section > a"

  - AGENT301:
      BOT_USERNAME: Agent301Bot
      REF_URL: https://t.me/Agent301Bot/app?startapp=onetime5024522783
      CLICKABLE_SELECTOR:
        - ""
  - UNION_EX:
      BOT_USERNAME: UnionEx_official_bot
      REF_URL: https://t.me/UnionEx_official_bot/UnionEx_Airdrop_Point?startapp=N52XDKbW
      CLICKABLE_SELECTOR:
        - "#root > div > div.min-h-\[calc\(100vh-40px\)\] > div > div > div.button.flex-shrink-0.h-\[45px\].w-full.bg-\[\#F4A800\].text-\[\#000\].rounded-\[6px\].flex.items-center.justify-center.text-\[22px\].font-bold"
        - "#root > div > div.min-h-\[calc\(100vh-40px\)\] > div > div.button.flex-shrink-0.h-\[45px\].w-full.bg-\[\#F4A800\].text-\[\#000\].rounded-\[6px\].flex.items-center.justify-center.text-\[22px\].font-bold"
        - "#root > div > div.min-h-\[calc\(100vh-40px\)\] > div > div.px-\[14px\].w-full > div"
        - "#root > div > div.min-h-\[calc\(100vh-40px\)\] > div > div.px-\[14px\].w-full > div"
        - "#root > div > div.min-h-\[calc\(100vh-40px\)\] > div.w-full.min-h-\[calc\(100vh-113px\)\] > div > div.button.flex-shrink-0.h-\[45px\].w-full.bg-\[\#F4A800\].text-\[\#000\].rounded-\[6px\].flex.items-center.justify-center.text-\[22px\].font-bold"

  - CAPYBARA_MEME:
      BOT_USERNAME: the_capybara_meme_bot
      REF_URL: https://t.me/the_capybara_meme_bot/start?startapp=c749201405a471872c338164f3727bdc
      CLICKABLE_SELECTOR:
        - "#q-app > div.pa-8.ta-c > div:nth-child(4) > div.mt-5.show-in.delay-2 > button"
        - "#q-app > div.pa-8 > div.show-in > button"
        - "#q-app > div.q-tab-panels.q-panel-parent.q-tab-panels--dark.q-dark > div > div > div > div.px-4 > button"
        - "#q-app > div.q-tab-panels.q-panel-parent.q-tab-panels--dark.q-dark > div > div > div > div.px-4 > button"
        - "#q-app > div.h-flex.h100p > div.flex-1.ov-a > div:nth-child(3) > div.pa-4 > div:nth-child(3) > div.mt-4 > button"
